name: Demo-01
on:
  push:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Print a message
        run: echo "Hello-World"
